# Generated by Django 4.1.7 on 2023-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_book_available',
            field=models.BooleanField(default=True),
        ),
    ]
